from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING

DEFAULT_RULES = {
    "fonts": {
        "chinese": "宋体",
        "western": "Times New Roman",
        "common_script_font": "宋体",
    },
    "spacing": {
        "require_space_between_cn_en": False,
        "require_space_between_cn_number": False,
        "require_space_between_en_number": True,
        "space_after_chinese_punctuation": "none",
        "space_before_chinese_punctuation": "none",
        "no_space_around_full_width_brackets": True,
        "no_space_after_full_width_punctuation_to_en_num": True,
    },
    "paragraph": {
        "论文正文": {
            "based_on": None,
            "is_default": True,
            "chinese_font": "宋体",
            "western_font": "Times New Roman",
            "common_script_font": "宋体",
            "font_size_pt": 12,
            "font_bold": False,
            "font_italic": False,
            "first_line_indent_cm": 0.85,
            "line_spacing_rule": WD_LINE_SPACING.MULTIPLE,
            "line_spacing_value": 1.25,
            "alignment": WD_ALIGN_PARAGRAPH.JUSTIFY,
            "space_before_pt": 0,
            "space_after_pt": 0,
            "keep_with_next": False,
            "keep_together": False,
            "widow_control": True,
            "require_space_between_cn_en": False,
            "require_space_between_cn_number": False,
        },
        "标题2": {
            "based_on": "论文正文",
            "chinese_font": "黑体",
            "western_font": "Times New Roman",
            "common_script_font": "黑体",
            "font_size_pt": 16,
            "font_bold": True,
            "font_italic": False,
            "first_line_indent_cm": 0,
            "line_spacing_rule": WD_LINE_SPACING.MULTIPLE,
            "line_spacing_value": 1.25,
            "alignment": WD_ALIGN_PARAGRAPH.CENTER,
            "space_before_pt": 18,
            "space_after_pt": 12,
            "keep_with_next": True,
            "keep_together": True,
            "widow_control": True,
            "require_space_between_cn_en": False,
            "require_space_between_en_number": True,
        },
        "Heading 1": {
            "based_on": "论文正文",
            "chinese_font": "黑体",
            "western_font": "Times New Roman",
            "common_script_font": "黑体",
            "font_size_pt": 16,
            "font_bold": True,
            "font_italic": False,
            "first_line_indent_cm": 0,
            "line_spacing_rule": WD_LINE_SPACING.MULTIPLE,
            "line_spacing_value": 1.25,
            "alignment": WD_ALIGN_PARAGRAPH.CENTER,
            "space_before_pt": 18,
            "space_after_pt": 12,
            "keep_with_next": True,
            "keep_together": True,
            "widow_control": True,
            "require_space_between_cn_en": False,
        },
        "Heading 2": {
            "based_on": "Heading 1",
            "chinese_font": "黑体",
            "western_font": "Times New Roman",
            "common_script_font": "黑体",
            "font_size_pt": 14,
            "font_bold": True,
            "font_italic": False,
            "first_line_indent_cm": 0,
            "line_spacing_rule": WD_LINE_SPACING.MULTIPLE,
            "line_spacing_value": 1.25,
            "alignment": WD_ALIGN_PARAGRAPH.LEFT,
            "space_before_pt": 12,
            "space_after_pt": 6,
            "keep_with_next": True,
            "require_space_between_cn_en": False,
        },
        "Heading 3": {
            "based_on": "Heading 2",
            "chinese_font": "宋体",
            "western_font": "Times New Roman",
            "common_script_font": "宋体",
            "font_size_pt": 12,
            "font_bold": True,
            "font_italic": False,
            "first_line_indent_cm": 0,
            "line_spacing_rule": WD_LINE_SPACING.MULTIPLE,
            "line_spacing_value": 1.25,
            "alignment": WD_ALIGN_PARAGRAPH.LEFT,
            "space_before_pt": 6,
            "space_after_pt": 6,
            "keep_with_next": True,
            "require_space_between_cn_en": False,
        },
        "图标题": {
            "chinese_font": "宋体",
            "western_font": "Times New Roman",
            "common_script_font": "宋体",
            "font_size_pt": 10.5,
            "font_bold": False,
            "font_italic": False,
            "first_line_indent_cm": 0,
            "line_spacing_rule": WD_LINE_SPACING.SINGLE,
            "alignment": WD_ALIGN_PARAGRAPH.CENTER,
            "space_before_pt": 6,
            "space_after_pt": 12,
            "keep_with_next": False,
            "require_space_between_cn_en": True,
        },
        "图": {
            "chinese_font": "宋体",
            "western_font": "Times New Roman",
            "common_script_font": "宋体",
            "font_size_pt": 10.5,
            "font_bold": False,
            "font_italic": False,
            "first_line_indent_cm": 0,
            "line_spacing_rule": WD_LINE_SPACING.SINGLE,
            "alignment": WD_ALIGN_PARAGRAPH.CENTER,
            "space_before_pt": 0,
            "space_after_pt": 0,
            "keep_with_next": False,
            "require_space_between_cn_en": False,
            "require_space_between_cn_number": True,
        },
        "表标题": {
            "chinese_font": "宋体",
            "western_font": "Times New Roman",
            "common_script_font": "宋体",
            "font_size_pt": 10.5,
            "font_bold": False,
            "font_italic": False,
            "first_line_indent_cm": 0,
            "line_spacing_rule": WD_LINE_SPACING.SINGLE,
            "alignment": WD_ALIGN_PARAGRAPH.CENTER,
            "space_before_pt": 12,
            "space_after_pt": 6,
            "keep_with_next": True,
            "require_space_between_cn_en": False,
        },
        "参考文献": {
            "chinese_font": "宋体",
            "western_font": "Times New Roman",
            "common_script_font": "Times New Roman",
            "font_size_pt": 10.5,
            "font_bold": False,
            "font_italic": False,
            "hanging_indent_cm": 0.85,
            "line_spacing_rule": WD_LINE_SPACING.SINGLE,
            "alignment": WD_ALIGN_PARAGRAPH.LEFT,
            "space_before_pt": 0,
            "space_after_pt": 3,
            "keep_with_next": False,
            "require_space_between_cn_en": True,
        },
        "摘要标题": {
            "based_on": "Heading 1",
            "chinese_font": "黑体",
            "western_font": "Times New Roman",
            "common_script_font": "黑体",
            "font_size_pt": 14,
            "font_bold": True,
            "alignment": WD_ALIGN_PARAGRAPH.CENTER,
            "space_before_pt": 24,
            "space_after_pt": 12,
            "require_space_between_cn_en": False,
        },
        "摘要正文": {
            "based_on": "论文正文",
            "chinese_font": "楷体_GB2312",
            "western_font": "Times New Roman",
            "common_script_font": "楷体_GB2312",
            "font_size_pt": 12,
            "line_spacing_rule": WD_LINE_SPACING.MULTIPLE,
            "line_spacing_value": 1.25,
            "alignment": WD_ALIGN_PARAGRAPH.JUSTIFY,
            "space_before_pt": 0,
            "space_after_pt": 0,
            "require_space_between_cn_en": False,
        },
    }
}
# --- 规则定义结束 ---

# 用于浮点数比较的容差
FLOAT_TOLERANCE = 0.01
PT_TOLERANCE = 0.5 # 磅值的容差，因为python-docx转换可能引入微小差异
CM_TOLERANCE = 0.01 # 厘米值的容差

# 中文字符和数字的正则表达式模式
RE_CHINESE = r'[\u4e00-\u9fff]'
RE_WESTERN = r'[a-zA-Z]'
RE_NUMBER = r'[0-9]'

RE_CHINESE_PUNCTUATION = "[︰﹐﹑﹒·﹔﹕‘’“”〝〞‵′〃『』「」﹁﹂﹃﹄﹙﹚〈〉﹝﹞﹖﹑]"
RE_FULL_WIDTH_BRACKETS_LEFT = "[（［｛【〖〔〈《「『]"
RE_FULL_WIDTH_BRACKETS_RIGHT = "[）］｝】〗〕〉》」』]"
# RE_CHINESE_PUNCTUATION = r'[。，！？；：（）《》【】“”‘’、]'
# RE_FULL_WIDTH_BRACKETS_LEFT = r'[（【《“‘]'
# RE_FULL_WIDTH_BRACKETS_RIGHT = r'[）】》”’]'
